-- AIRPALAB 문의 테이블 예시
-- Supabase SQL Editor에서 실행 전 기존 스키마와 테이블명을 반드시 확인하세요.

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  category text not null check (char_length(category) <= 50),
  name text not null check (char_length(name) <= 50),
  email text not null check (char_length(email) <= 200),
  message text not null check (char_length(message) <= 5000),
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

-- 익명/로그인 사용자가 문의를 등록할 수 있도록 INSERT만 허용
drop policy if exists "public can submit inquiries" on public.inquiries;
create policy "public can submit inquiries"
on public.inquiries
for insert
to anon, authenticated
with check (true);

-- SELECT/UPDATE/DELETE 정책은 만들지 않음:
-- 브라우저 anon key로 문의 목록을 읽거나 수정/삭제할 수 없게 하는 기본 구성입니다.
-- 운영자는 Supabase Dashboard 또는 서버측(service_role) 환경에서 관리하세요.
